### ISSUE TITLE
Handle error objects properly

### ISSUE THREAD

**Issue by adamkdean** [edge/log#13]
When passing an Error object to the log, it isn't handling these properly, and instead just displays `{}`.

Take the following example:

```ts
// Handle unhandled promises
process.on('unhandledRejection', (reason: unknown) => {
  this.log.error('Unhandled promise rejection', { reason})
  console.error(reason)
})
```

And now compare the log output with regular console output (truncated for readability):

```
15:37:30.060  ERR  [example] Unhandled promise rejection {"reason":{}}
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    ...
```

We need log to be able to properly handle errors when passed in as the context. Whether this is stringifying a stack trace or extracting information from the error object. This can be easily reproduced by throwing an error with a custom message.

**Comment by annybs** [comment]
I've investigated a little further and find the error displays correctly if passed as the message or as the de facto context. There is only a problem when the error is passed as a context _property:_

```js
log.error(msg)
// 👉 10:20:49.383  ERR  {"error":"Error: nothing is wrong, just checking","stack":"Error: nothing is wrong, just checking\n    at Object.<anonymous> [...]

log.error('will it serialize?', msg)
// 👉  10:24:39.239  ERR  will it serialize? {"error":"Error: nothing is wrong, just checking","stack":"Error: nothing is wrong, just checking\n    at Object.<anonymous> [...]

log.error('will it serialize???', { msg })
// 👉 10:24:39.240  ERR  will it serialize??? {"msg":{}}
```

This is because the function pair of `disambiguate` + `mergeContexts` has the side effect of treating the error as an object and copying out its properties, whereas an `Error` proper doesn't enjoy the luxury of preprocessing.
