### ISSUE TITLE
Context grey background persisting to newline

### ISSUE THREAD

**Issue by adamkdean** [edge/log#8]
![example](https://user-images.githubusercontent.com/1639527/136062224-9dd3ed86-d32b-4bde-997b-0a6e0c907a3e.png)

The grey shouldn't extend to the end of the line

**Comment by annybs** [comment]
I've investigated, and as discussed on Discord this appears to be a side effect of terminal rendering behaviour rather than the chalk package itself. To illustrate, a screenshot with wrapped data from my VS Code terminal:

![image](https://user-images.githubusercontent.com/129557/137115377-308d062e-bf62-4329-bd62-43b0e28a4e38.png)

The same again, but with a much wider pane:

![image](https://user-images.githubusercontent.com/129557/137115448-f890422d-c3f2-4e4b-92e7-658e4b87d6d5.png)

We see here that the background colour doesn't stretch to the end of the line, it stops where we expect it to.

For contrast, I've also checked in the OSX terminal, and that doesn't exhibit the same problem even when the lines with grey background wrap:

![image](https://user-images.githubusercontent.com/129557/137115978-70245c4f-758c-4c0f-928f-3b5e1b50c074.png)

As such, we'll have to call this a wontfix. We can work around it by changing the implementation, e.g. not having a background colour in the first place, but that would be out of scope for this issue.
